godaddy:
  username: "example"
  password: "secret"
  hostname: "test"
  type: "A"

log:
  file: "/var/log/godaddy-ddns.log"
  level: "debug"
  max_size: 1024

ip:
  file: "/opt/godaddy-ddns/current-ip.txt"